In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


###  Random Tensors

why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random nubers and then adjust those random numbers to better represent the data.

'Start withrandom numbers -> look ata data -> update random numbers -> look at data -> update random numbers

In [ ]:
#Create a random tensor of size(3,4)
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.4178, 0.6747, 0.4808, 0.7592],
        [0.7722, 0.7413, 0.0349, 0.8514],
        [0.7528, 0.8140, 0.0486, 0.6278]])

In [ ]:
random_tensor.ndim

2

##MY OWN EXAMPLES FOR RANDOM-TENSOR

In [ ]:
#Create a random tensor of size(3,4)
random_tensor =torch.rand(10,10)
random_tensor

tensor([[0.5770, 0.5080, 0.1152, 0.5607, 0.7711, 0.5109, 0.7654, 0.7761, 0.0891,
         0.9157],
        [0.5376, 0.3144, 0.7173, 0.8443, 0.4954, 0.9409, 0.3878, 0.7492, 0.9445,
         0.8573],
        [0.6191, 0.0612, 0.4526, 0.2744, 0.5891, 0.5632, 0.9022, 0.8693, 0.8456,
         0.6635],
        [0.2111, 0.0826, 0.0599, 0.1704, 0.8565, 0.8867, 0.7480, 0.7461, 0.8149,
         0.2352],
        [0.8092, 0.0587, 0.6027, 0.6863, 0.1900, 0.6206, 0.2989, 0.8508, 0.6842,
         0.6061],
        [0.8870, 0.9660, 0.7515, 0.6028, 0.6342, 0.4320, 0.7670, 0.3722, 0.3521,
         0.3808],
        [0.8967, 0.3143, 0.0979, 0.4279, 0.2124, 0.0990, 0.8636, 0.6071, 0.6480,
         0.1295],
        [0.9561, 0.1882, 0.5044, 0.9094, 0.0240, 0.1858, 0.9180, 0.4896, 0.3802,
         0.1484],
        [0.0508, 0.3625, 0.9876, 0.6257, 0.8981, 0.4813, 0.9143, 0.2578, 0.1585,
         0.3574],
        [0.5071, 0.8178, 0.5401, 0.3743, 0.9013, 0.5475, 0.1963, 0.4174, 0.0033,
         0.4581]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor of size(3,4)
random_tensor =torch.rand(10,10),10
random_tensor

(tensor([[0.4782, 0.8109, 0.4915, 0.9259, 0.4715, 0.2908, 0.0145, 0.9255, 0.7414,
          0.5864],
         [0.4371, 0.0014, 0.3601, 0.6399, 0.2383, 0.6984, 0.1029, 0.2098, 0.7464,
          0.5544],
         [0.4097, 0.4625, 0.9646, 0.0454, 0.4031, 0.9805, 0.0564, 0.9785, 0.1210,
          0.1332],
         [0.4885, 0.8101, 0.2472, 0.4538, 0.8530, 0.7798, 0.5239, 0.2322, 0.9907,
          0.4500],
         [0.2907, 0.7029, 0.1994, 0.4989, 0.7820, 0.6561, 0.7892, 0.8841, 0.9757,
          0.7350],
         [0.7421, 0.4027, 0.6903, 0.3281, 0.3191, 0.8618, 0.1797, 0.6832, 0.8470,
          0.6315],
         [0.2558, 0.8162, 0.0187, 0.9136, 0.9018, 0.5272, 0.9089, 0.5895, 0.2040,
          0.8329],
         [0.5560, 0.9560, 0.5594, 0.2250, 0.3803, 0.2469, 0.5124, 0.5410, 0.7751,
          0.5760],
         [0.5581, 0.2525, 0.3691, 0.2525, 0.6024, 0.9516, 0.5291, 0.9646, 0.1224,
          0.2797],
         [0.4513, 0.5404, 0.6410, 0.6308, 0.0467, 0.2641, 0.9262, 0.1630, 0.1390,
         

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor =torch.rand(size=(224,224,3))#height,width,colour channels (R ,G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
#Create a tensor of all zeros
zeros =torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones =  torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32