###Creating a range of tensors and tensors-like

In [30]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [31]:
#Use torch.range()
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
one_to_ten = torch.arange(start =0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:

one_to_ten = torch.arange(start =0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [34]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start =1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# Creating tensors like
ten_zeros = torch.zeros_like(input =one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes


**Note:** Tensor datatypes is one of the 3 big errors you'll run into Pytorch & deep Learning

####1.  Tensors not right datatype
####2.  Tensors not right shape
####3.  Tensors not on the right device

In [42]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0 , 6.0 , 9.0],
                               dtype=None,  #What datatype is a is the tensor(e.g float32 or float16)
                               device=None,#what device is your tensor on
                               requires_grad=False) #whether or not to track gradients via with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [46]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [47]:
int_32_tensor =torch.tensor([3 , 6 , 9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [48]:
int_32_tensor =torch.tensor([3 , 6 , 9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [49]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
  

  1.Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

  2.Tensors not right shape - to get shape from a tensor,can use `tensor.shape`
  
  3.Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [50]:
# Create a tensor
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.6967, 0.9965, 0.8711, 0.3265],
        [0.5666, 0.4107, 0.9145, 0.2774],
        [0.9925, 0.9017, 0.1993, 0.5595]])

In [52]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.6967, 0.9965, 0.8711, 0.3265],
        [0.5666, 0.4107, 0.9145, 0.2774],
        [0.9925, 0.9017, 0.1993, 0.5595]])
Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (tensor operations)


Tensor operation include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [55]:
# Create a tensor and add 10 to it
tensor =torch.tensor([1 , 2 , 3])
tensor + 10

tensor([11, 12, 13])

In [56]:
# Create a tensor and multiply 10 to it
tensor =torch.tensor([1 , 2 , 3])
tensor * 10

tensor([10, 20, 30])

In [57]:
tensor * 10

tensor([10, 20, 30])

In [58]:
# Create a tensor and Subtract 10 to it
tensor =torch.tensor([1 , 2 , 3])
tensor -  10

tensor([-9, -8, -7])

In [59]:
# Try out pytorch in-built functions
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [62]:
torch.add(tensor , 10)

tensor([11, 12, 13])

## Matrix multiplication
Two main ways of performing multiplication in networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)


There are two main rules that are performingmatrix multiplication needs to satisfy:
1. The **inner dimensions** must match:

    * `(3,2) @ (3,2)` won't work

    * `(2,3) @ (3,2)` will work

    * `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

 * `(2,3) @ (3,2)` -> `(2, 2)`
 * `(3,2) @ (3,2)` -> `(2, 2)`

In [77]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7929, 1.4389],
        [0.9599, 1.4516]])

In [78]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3479, 0.4675, 0.9371],
        [0.3226, 0.4973, 1.0442],
        [0.3300, 0.4348, 0.8652]])

In [79]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[0.9098, 2.3734, 2.2058],
        [2.4230, 3.8972, 3.8401],
        [1.6806, 2.2315, 1.7114]])

In [80]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[1.7820, 2.2375, 1.9768, 2.6945, 2.4749, 2.2129, 2.5659, 2.1405, 2.9659,
         2.8671],
        [1.5490, 2.0439, 1.5889, 2.2256, 1.9370, 1.8169, 2.1933, 1.7962, 2.6116,
         2.4646],
        [2.1565, 2.4173, 2.1728, 2.5021, 2.5308, 2.5004, 2.8093, 2.8237, 3.8567,
         2.7252],
        [1.5113, 1.7095, 1.6345, 1.5240, 2.0369, 1.9697, 2.1170, 2.0925, 2.9925,
         2.1429],
        [1.6995, 1.8197, 1.1164, 1.9717, 2.3454, 1.3770, 2.2024, 1.6475, 2.5307,
         2.0416],
        [2.0773, 2.1094, 1.3131, 2.1462, 2.8053, 2.4395, 2.8221, 2.3885, 3.2116,
         2.6650],
        [2.4143, 2.8197, 2.4285, 3.0480, 3.1915, 2.8447, 3.1632, 2.5437, 3.9955,
         3.6414],
        [1.8006, 1.9186, 1.8970, 1.6708, 2.2385, 1.8162, 2.1586, 2.1705, 3.4666,
         2.2184],
        [1.6826, 2.0976, 1.7284, 1.8564, 2.1435, 2.1445, 2.1047, 2.2877, 3.1690,
         2.5005],
        [1.7201, 2.1581, 1.7538, 1.9796, 2.1234, 2.1148, 2.3696, 2.0670, 3.2355,
         2.5819]])

In [63]:
# Element wise multiplication
print(tensor, "*" ,tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [69]:
# Element wise multiplication
print(tensor, "*" , tensor)
print(f"Equals:({tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:(tensor([1, 4, 9])


In [70]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [71]:
tensor

tensor([1, 2, 3])

In [72]:
# Matrix multiplication by Hand
1 * 1 + 2 * 2 + 3 * 3


14

In [75]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 1.85 ms, sys: 0 ns, total: 1.85 ms
Wall time: 1.78 ms


In [76]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 438 µs, sys: 40 µs, total: 478 µs
Wall time: 481 µs


tensor(14)