## Indexing(selecting data from tensors)
#### Indexing with Pytorch is smililar to indexing with Numpy

In [2]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
#Lets index on our new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
# Let's index on the middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [5]:
#Let's index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [6]:
#Let's index on the most inner bracket (last dim)
x[0][1][1]

tensor(5)

In [7]:
# You can also use":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [8]:
# Get all the values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [9]:
# Get index 0 of 0th and 1st dimension and all values od 2nd dimension
x[0,0,:]


tensor([1, 2, 3])

In [10]:
# Index on x to return 9
print(x[0][2][2])
#Index on x to return 3,6,9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [11]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Pytorch tensors & Numpy
Numpy is a popular scientific python numerical computing library.
and becaue of this,Pytorch has functionality to interact with it.

* Data in Numpy,want in Pytorch tensor->`torch.form_numpy(ndarray)`
*Pytorch tensor ->Numpy ->`torch.Tensor.numpy()`

In [12]:
## Pytorch tensors & Numpy
# Numpy array to tensor
import torch
import numpy as np
array =np.arange(1.0,8.0)
tensor =torch.from_numpy(array) # warning: when converting from numpy -> pytorch reflects numpy's default of float64  unless specified oterwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
array.dtype

dtype('float64')

In [14]:
# Change the value of array , what will tis do to `tensor'?
array=array+1
array,tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [15]:
# Tensor to Numpy array
tensor =torch.ones(7)
numpy_tensor =tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [16]:
numpy_tensor.dtype

dtype('float32')

In [17]:
# Change the tensor ,what happens to 'numpy_tensor`?
tensor =tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)
In short how a neural network learns:


`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again ->....`
  

To reduce the randomness in neutral networks and pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [20]:
import torch

# Create two random tensors
random_tensor_A =torch.rand(3,4)
random_tensor_B =torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5813, 0.7489, 0.0478, 0.7116],
        [0.3582, 0.1893, 0.9520, 0.4807],
        [0.3023, 0.6545, 0.4112, 0.6106]])
tensor([[0.4952, 0.1837, 0.1974, 0.4223],
        [0.9911, 0.6545, 0.0538, 0.2912],
        [0.9927, 0.6706, 0.1401, 0.3819]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [26]:
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers,thanks to CUDA + NVIDIA  hardwware + Pytorch working behind the scenes to make everything hunky dory(good)

### 1. Getting a GPU

In [3]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

False