##Finding the min,max,mean,sum,etc(tensor aggregation)

In [16]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [28]:
#create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [29]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [30]:

# Find the max
#Find the min
torch.max(x), x.max()

(tensor(91), tensor(91))

In [31]:
## Find the mean -note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [32]:
# Find the sum
torch.sum(x), x.sum()


(tensor(460), tensor(460))

## Finding the positional min and max

In [33]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position  of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [35]:
x[0]

tensor(1)

In [36]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [37]:
x[9]

tensor(91)

In [38]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping ,stacking, sqeezing and unsqeezing tensors

* Reshaping -reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on the top of each other (vstack) or side by side (hstack)
* Sqeeze - removes all`1` dimensions from a tesnor
* Unsqueeze - add a `1` dimension from a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [40]:
# Let's create a tesnor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [44]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
# Changing z changes x( because a view of a tensor shares the same memory as the original input )
z [:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
# Stack tensors on top of each other
x_stacked =torch.stack([x ,x ,x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape:{x_reshaped.shape}")
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")

print(f"New shape:{x_squeezed.shape}")



Previous tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape:torch.Size([9, 1])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [54]:
x_reshaped.shape


torch.Size([9, 1])

In [52]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
x_reshaped.squeeze().shape

torch.Size([9])

In [57]:
# torch.unsqueeze() -adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

# Add an extra dimension with unsqeeze
x_unsqueezed =x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor:{x_unsqueezed}")
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [59]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))# [height ,width,colour_channels]
#permute the original tensor to rearrange the axix(or dim)order
x_permuted =x_original.permute(2,0,1) ##shifts axis 0->1, 1->2, 2->0
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}") # [colour_channels,height,width]


Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [58]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
x_original

tensor([[[7.2822e+05, 2.8783e-02, 6.9867e-01],
         [8.0005e-01, 7.4599e-01, 2.3262e-01],
         [7.1709e-01, 8.3820e-01, 4.8962e-01],
         ...,
         [5.5891e-01, 6.5859e-01, 5.1384e-01],
         [1.1952e-01, 9.2795e-02, 5.1790e-01],
         [9.2293e-01, 3.8218e-02, 5.9752e-01]],

        [[5.7013e-01, 7.8323e-01, 1.5295e-01],
         [5.3222e-01, 6.6589e-01, 8.5245e-01],
         [6.7877e-01, 4.5178e-01, 3.2388e-01],
         ...,
         [2.0257e-01, 5.8777e-01, 8.4281e-01],
         [2.5724e-01, 7.1069e-01, 4.7057e-01],
         [6.9722e-01, 4.2366e-01, 9.2588e-01]],

        [[4.7445e-01, 3.7084e-02, 4.2466e-01],
         [4.4189e-01, 1.0549e-02, 7.4295e-01],
         [5.6612e-01, 2.8635e-01, 3.7049e-01],
         ...,
         [6.1179e-01, 2.3098e-01, 1.4021e-01],
         [8.8329e-01, 5.2146e-01, 3.5858e-01],
         [6.7844e-01, 6.4406e-01, 7.6828e-01]],

        ...,

        [[8.9804e-01, 5.6817e-01, 1.1309e-01],
         [5.6520e-03, 1.8029e-01, 6.3046e-01]

In [65]:
x_original[0, 0 ,0]= 728218


In [66]:
x_original[0 ,0 ,0]=728218
x_original[0 ,0 ,0], x_permuted[0,0,0]


(tensor(728218.), tensor(728218.))